title: egg
description: >- # this means to ignore newlines until "baseurl:"
  egg: e-graphs good
baseurl: ""
url: "https://egraphs-good.github.io/"

permalink: /:categories/:title
# markdown: kramdown
# collections:
#   papers:
#     permalink: /:collection/:name:output_ext
#     output: true
